server:
  port: 8001
  
spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.183.183:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 520000ww

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #,http://eureka7002.com:7002/eureka  #集群版
      #defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.syf.springcloud.entities



