
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.183.183:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 520000ww
  redis:
    database: 0
    port: 6021
    host: localhost
    password:
    jedis:
      pool:
        max-active: 200  #连接池最大连接数
        max-idle: 10 #最大空闲数
        min-idle: 1 #最小空闲数
        max-wait: -1  #连接池最大阻塞等待时间（负值表示没有限制）
server:
  port: 8083

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.syf.springcloud.entities